services:
  - type: web
    name: tender-generator-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://kartik:kartik@cluster0.tdwlgsp.mongodb.net/
      - key: JWT_SECRET
        value: kartik
      - key: GOOGLE_CLIENT_ID
        value: 237308786705-nsr1qgam8usomo78970sble2m5cnbncr.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: FRONTEND_URL
        value: https://tender-generator-frontend.vercel.app